# Generated by Django 3.2.7 on 2021-09-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0002_alter_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
