# Generated by Django 3.2.7 on 2021-10-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ask', to='Q_A.user'),
            preserve_default=False,
        ),
    ]
