# Generated by Django 3.2.7 on 2021-10-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0005_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
